version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres-pisadev
    ports:
      - 5432:5432
    # User/password for local dev: root/password
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pisadev
