version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mysql-pisadev
    ports:
      - 3306:3306
    # User/password for local dev: root/password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pisadev
